name: Release and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test:run

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Build production bundle
        run: pnpm build

      - name: Create deployment archive
        run: |
          cd dist
          tar -czf ../flashcards-${{ github.ref_name }}.tar.gz .
          cd ..

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Flash Cards ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Production-ready multiplication flash cards application

            ## Features
            - 241/241 tests passing, 0 TypeScript errors, 0 lint warnings
            - Mobile-first React 18 + TypeScript 5 + Tailwind CSS v4
            - Intelligent adaptive learning with weighted randomization
            - User management and session tracking
            - Progress reports with analytics charts

            ## Technology Stack
            - Build: Vite 6
            - Styling: Tailwind CSS v4
            - Router: React Router DOM 6.28
            - Charts: Recharts 2.13
            - Testing: Vitest 3.2 + Playwright

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flashcards-${{ github.ref_name }}.tar.gz
          asset_name: flashcards-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Trigger deployment webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          PAYLOAD='{
            "action": "published",
            "release": {
              "tag_name": "${{ github.ref_name }}",
              "name": "Flash Cards ${{ github.ref_name }}",
              "html_url": "https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
            },
            "repository": {
              "full_name": "${{ github.repository }}",
              "clone_url": "https://github.com/${{ github.repository }}.git"
            }
          }'
          SIGNATURE="sha256=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | sed 's/^.* //')"
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: release" \
            -H "X-Hub-Signature-256: $SIGNATURE" \
            -d "$PAYLOAD"
